# Setup
setup: end2end

# Model
backbone: resnet34
model_kwargs:
   head: mlp
   features_dim: 128
   nheads: 1
   nclusters: 200

# Dataset
train_db_name: tiny_imagenet
val_db_name: tiny_imagenet
num_classes: 200
num_neighbors: 5

# Loss
criterion: end2end
criterion_kwargs:
    #temperature: 0.5
   temperature: 0.1
   entropy_weight: 2.0

# Hyperparameters
epochs: 1000

#optimizer: adam
#optimizer_kwargs:
#   weight_decay: 0.0
#   lr: 0.0003
#scheduler: constant
#
optimizer: sgd
optimizer_kwargs:
   nesterov: False
   weight_decay: 0.0001 
   momentum: 0.9
   lr: 0.4
scheduler: cosine
scheduler_kwargs:
   lr_decay_rate: 0.1

batch_size: 128
num_workers: 8

# Transformations
augmentation_strategy: simclr 
augmentation_kwargs:
   random_resized_crop:
      size: 64
      scale: [0.2, 1.0]
   color_jitter_random_apply:
      p: 0.8
   color_jitter:
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1
   random_grayscale: 
      p: 0.2
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

transformation_kwargs:
   resize: 80
   crop_size: 64
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
